# Generated by Django 4.2 on 2023-04-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
